apiVersion: v1 
kind: ReplicationController 
metadata: 
  name: hopper-rc
spec: 
  replicas: 3 
  selector:
    app: hopperapp
  template:
    metadata:
      labels:
        app: hopperapp 
    spec:
      containers:
        - name: hopper 
          image: phyominhtun/hopper-build
          ports: 
          - containerPort: 80
