apiVersion: v1
kind: Service
metadata:
  name: hopper-headless-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  clusterIP: None 
status:
  loadBalancer: {}
