apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    app: unicorn 
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: unicorn 
  type: LoadBalancer
