apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: hopper-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hopperapp
  type: NodePort
status:
  loadBalancer: {}
