apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1-stroageclass
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data1
