apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim-1-storageclass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: hostpath 
