apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-with-hostpath
spec:
  storageClassName: pv-hostpath
  capacity:
    storage: 10Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/Users/phyominhtun/Documents/kubernetes-yaml/volume/minikube-data" #host location

