# pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: third-pvc
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-ssd
  