apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-with-pv-hostpath
spec:
  storageClassName: pv-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
