apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi  
spec:
  containers:
  - image: nginx:1.9.1
    name: nginx-container
  - image: redis 
    name: redis-container   
