apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pay-ingress
  namespace: critical-space
spec:
  rules:
  - http:
      paths:
      - path: /pay
        backend:
          serviceName: pay-service
          servicePort: 8282 ### SVC NodePort
