apiVersion: v1
kind: Pod
metadata:
  labels:
    run: elephant
  name: elephant
spec:
  containers:
  - image: polinux/stress
    name: elephant
    resources: 
      requests:
        memory: "5Mi"
        cpu: "250m"
      limits:
        memory: "20Mi"
        cpu: "500m"
