apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - name: redis-secret
    image: redis
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/mysecret"
  volumes:
  - name: secret-volume
    secret:
      secretName: db-creds
